config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

#creating routes for posts and comments
resources :posts do
	resources :comments
end

#Gets the contacts path for the contacts new function
get 'contacts', to: 'contacts#contact'

#Gets the request contacts path for the contacts request contacts function
post 'request_contacts', to: 'contacts#request_contacts'

#Gets the activities path for the activities index function
get 'activities', to: 'activities#index'

#get about us
get 'about', to: 'posts#about'
#generates resources for the rest of controllores
resources :countries
resources :activities

#Sets a root path
root 'posts#index'


#ends routes
end

app/models/activity.rb
class Activity < ApplicationRecord
	#An activity can have many countries
	has_many :countries

	validates :name, presence: true
	validates :description, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	#One comment only belongs to one post
	belongs_to :post

	validates :name, presence: true
	validates :comment, presence: true

end

app/models/country.rb
class Country < ApplicationRecord
	#Many countries have many different activities
	has_many :activities

	validates :name, presence: true
	validates :description, presence: true
	validates :link, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
	#One post has manny comments
	has_many :comments

	validates :title, presence: true
	validates :content, presence: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
before_action :find_activity, only: [:show, :update, :edit, :destroy]
before_action :find_countries, only: [:index, :show, :new, :edit]

#before_action :set_activity, only: [:create]
	#method to show all the activities
	def index
		@activities = Activity.all.order("created_at DESC")
	end

	# method for a new activity
	def new
		@activity = Activity.new
	end

	#method for create a new activity
	def create
		@activity = Activity.new(activity_params)
	respond_to do |format|
			if @activity.save
				format.html { redirect_to root_path, notice: "made activity" }
			else
				format.html { render new }
			end
		end
	end


  #Show method
	def show

	end

  #Delete activity
	def destroy
		@activity.destroy
		#After deleting activity redirect the user to activities index
		redirect_to activities_path

	end

  #Strong parameteres
	private

  #Defining strong parameteres for activities
	def activity_params
		params.require(:activity).permit(:name, :description, :countries_id)
	end

	def find_activity
	 	@activity = Activity.find(params[:id])
	end

	def find_countries
        @countries = Country.all.order('created_at desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	#method for create a new comment
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comments_params)
		redirect_to post_path(@post)
	end

	#Delete Comment
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

  #Strong parameteres
	private
	#Defining strong parameteres for comments
	def comments_params
		params.require(:comment).permit(:name, :comment)

	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController


	#method for create a new contact form
	def contacts
	end

	#Method for after the contact has been made
	def request_contacts
		name = params[:name]							
		email = params[:email]
		telephone = params[:telephone]
		message = params[:message]
		if email.blank?
		flash[:alert] = I18n.t('request_contacts.no_email')
		else
			ContactMailer.contact_email(email, name, telephone, message).deliver_now
		# Send an email
		flash[:notice] = I18n.t('request_contacts.email_sent')
		end
		redirect_to root_path


	end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
	before_action :find_country, only: [:show, :destroy]
	#Method for show all countries
	def index
				@countries = Country.all.order("created_at DESC")
	end

	#Method for new country
	def new
				@country = Country.new
	end

	#Method for create a new country
	def create
			@country = Country.new(country_params)

			#if the country has been saved successfully redirects to index of countries
			if @country.save
				redirect_to countries_path
			else
				render 'new'
			end
	end

	def show

	end

	def destroy
		@country.destroy
		#After deleting post redirect the user to countries index
		redirect_to countries_path

	end

	private
	#Defining strong parameteres for countries
	def country_params
		params.require(:country).permit(:name, :description, :link)
	end

	def find_country
		@country = Country.find(params[:id])
	end

end

app/controllers/posts_controller.rb
#Posts Controller
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :update, :edit, :destroy]

	#method to show all the posts
	def index
		@posts = Post.all.order("created_at DESC")
	end

	# method for a new post
	def new
		@post = Post.new
	end

	#method for create a new post
	def create
		@post = Post.new(post_params)

		#if the post has been saved redirects to index of posts
		if @post.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	#Show method
	def show
	end
	#Method to linkk to the about page

	def about
	end

	#Method to update the post
	def update
		#If a post has the post parameteres (title and content) redirect to the index of posts
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def edit
	end

	#Delete Post
	def destroy
		@post.destroy
		#After deleting post redirect the user to posts index
		redirect_to posts_path

	end

	#Strong parameteres
	private

	#Defining strong parameteres for posts
	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
	 	@post = Post.find(params[:id])
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activties_helper.rb
module ActivtiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/activities/_form.html.erb
<div class="section">
	<%= simple_form_for @activity do |f| %>
	<div class="field">
		<div class="control">
		<%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>

<div class="field">
	<div class="field">
		<div class="control">
		<%= f.input :description, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>

	<div class="field">
      <div class="control">
        <span class="select">
          <%= f.input_field :country_id, collection:@countries.map { |c| [c.name, c.id] }, prompt: "Select Country" %>
        </span>
      </div>
		</div>

	<%= f.button :submit, class: "button is-primary" %>

		<% end %>
</div>

app/views/activities/edit.html.erb
<%= content_for :page_title, "Edit activity" %>


<%= render 'form' %>

app/views/activities/index.html.erb
<%= content_for :page_title,  "All the activities" %>

<div class="section">
	<div class="container">
		<div class="box" >
		<% @activities.each do |activity| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to activity.name, activity  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= activity.description %>
		    </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>
</div>

app/views/activities/new.html.erb
<%= content_for :page_name, "Create a new activity" %>

<%= render 'form' %>

app/views/activities/show.html.erb
<%= content_for :activity_name, @activity.name %>

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		      <strong><%= @activity.name %></strong>  
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">

		  	<p class="level-item">
				<%= link_to "Delete", activity_path(@activity), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

		<div class="content">
			<%= @activity.description %>
		</div>
	</div>
</section>

app/views/comments/_comment.html.erb
<div class="box">
	<article class="media">
		<div class="media-content">
			<div class="content">
			<p>
				<strong><%= comment.name %>
				</strong>
				<%= comment.comment %>
			</p>
			
			</div>
		</div>

		<%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" } %>
		
	</article>
	
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

	<div class="field">
		<div class="control">	
		<%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>		
		</div>
	</div>

<div class="field">
	<div class="control">
		<div class="control">	
		<%= f.input :comment, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>		
		</div>
	</div>

	<%= f.button :submit, 'Leave a reply', class: "button is-primary" %>

		<% end %>

app/views/contacts/contact.html.erb

<h1>
  <%= t('.title') %>
</h1>
<p>

  <%= t('.contact_us') %>
</p>

<%= form_tag request_contacts_path, method: 'post' do %>
  <%= label_tag :name, t('.name') %>
  <%= text_field_tag :name, '', title: t('.enter_name'), size: 50 %>

  <%= label_tag :email, t('.email') %>
  <%= email_field_tag :email, '', title: t('.enter_email') %>

  <%= label_tag :telephone, t('.telephone') %>
  <%= telephone_field_tag :telephone, '', title: t('.enter_telephone') %>

  <%= label_tag :message, t('.message') %>
  <%= text_field_tag :message, '', title: t('.enter_message'), size: 100 %>


  <%= submit_tag t('contacts.submit') %>
<% end %>

app/views/contacts/new.html.erb

<h1>
  <%= t('.title') %>
</h1>
<p>

  <%= t('.contact_us') %>
</p>

<%= form_tag request_contacts_path, method: 'post' do %>
  <%= label_tag :name, t('.name') %>
  <%= text_field_tag :name, '', title: t('.enter_name'), size: 50 %>

  <%= label_tag :email, t('.email') %>
  <%= email_field_tag :email, '', title: t('.enter_email') %>

  <%= label_tag :telephone, t('.telephone') %>
  <%= telephone_field_tag :telephone, '', title: t('.enter_telephone') %>

  <%= label_tag :message, t('.message') %>
  <%= text_field_tag :message, '', title: t('.enter_message'), size: 100 %>


  <%= submit_tag t('contacts.submit') %>
<% end %>

app/views/countries/_form.html.erb
<div class="section">
	<%= simple_form_for @country do |f| %>
	<div class="field">
		<div class="control">
		<%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>

<div class="field">
	<div class="field">
		<div class="control">
		<%= f.input :description, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>


	<div class="field">
			<div class="control">
    			<%= f.input :link, input_html: {class: 'link' }, wrapper: false, label_html: { class: 'label'} %>
			</div>
  </div>

	<div class="button is-link">
		<div class="control">
				<%= f.button :submit, class: "button is-primary" %>
		</div>
	</div>


		<% end %>
</div>

app/views/countries/index.html.erb
<%= content_for :page_title,  "All the countries" %>

<div class="section">
	<div class="container">
		<div class="box" >
		<% @countries.each do |country| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to country.name, country  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= country.description %>
		    </div>


          <div class="button is-link">
            <%= country.link %>
          </div>
		    </div>
		  </div>
		</div>
		<% end %>
	</div>

app/views/countries/new.html.erb
<%= content_for :page_title, "Create a new country" %>

<%= render 'form' %>

app/views/countries/show.html.erb
<%= content_for :page_title, @country.name %>

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong><%=@country.name%></strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">

		  	<p class="level-item">
				<%= link_to "Delete", country_path(@country), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>

		<div class="content">
			<%= @country.description %>
      <a class="button is-link is-outlined ">
        <%= @country.link %>
      </a>
		</div>


	</div>
</section>

app/views/layouts/_footer.html.erb
<div id= "push"></div>
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <nav>
        <ul>
          <li><%=link_to "Contact Us", contacts_path %></li>
        </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item">

      <h1><%= link_to "planeahead", root_path %></h1>
    </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">


      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Posts
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
              <%= link_to 'posts', posts_path %>
          </a>
          <a class="navbar-item">
          <%= link_to 'new post', new_post_path %>
          </a>


        </div>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Activities
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
              <%= link_to 'Index of all Activties', activities_path %>
          </a>
          <a class="navbar-item">
            <%= link_to 'Create a new activity', new_activity_path %>
          </a>
          <a class="navbar-item">
            <!--<%#= link_to 'Edit your activity', edit_activity %> !-->
          </a>
          <hr class="navbar-divider">

        </div>

        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Countries
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item">
                <%= link_to 'Index of all Countries', countries_path %>
            </a>
            <a class="navbar-item">
              <%= link_to 'Add a new country to edit', new_country_path %>
            </a>

            <hr class="navbar-divider">

          </div>
          <a class="navbar-item">

            <h1><%= link_to 'About Us', about_path %></h1>
          </a>

      </div>
    </div>


  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plane Ahead</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if notice %>
  <p class="alert alert-success">
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger">
    <%= alert %>
  </p>
<% end %>


  <body>
    <%= render 'layouts/header'%>
    <section class="section">
    <%= yield %>
    </section>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="section">
	<%= simple_form_for @post do |f| %>
	<div class="field">
		<div class="control">
		<%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>

<div class="field">
	<div class="field">
		<div class="control">
		<%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: { class: 'label'} %>
		</div>
	</div>

	<%= f.button :submit, class: "button is-primary" %>

		<% end %>
</div>

app/views/posts/about.html.erb
<p>This website will help you to find several fun activities that you can do in different countries. So get started and plane ahead
</p>

app/views/posts/edit.html.erb
<%= content_for :page_title, "Edit post" %>


<%= render 'form' %>

app/views/posts/index.html.erb
<%= content_for :page_title,  "Index" %>

<div class="section">
	<div class="container">
		<div class="box" >
		<% @posts.each do |post| %>
			<div class="card">
		  <div class="card-content">
		    <div class="media">
		      <div class="media-content">
		        <p class="title is-4"><%= link_to post.title, post  %></p>
		      </div>
		    </div>
		    <div class="content">
		     	<%= post.content %>
		    </div>
		    </div>
		  </div>
		</div>
		<% end %>
		</div>
	</div>

app/views/posts/new.html.erb
<%= content_for :page_title, "Create a new post" %>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= content_for :page_title, @post.title %>

<section class="section">
	<div class="container">
		<nav class="level">
		  <!-- Left side -->
		  <div class="level-left">
		    <p class="level-item">
		        <strong>Posts</strong>
		    </p>
		  </div>
		  <!-- Right side -->
		  <div class="level-right">
		  	<p class="level-item">
		    	<%= link_to "Edit", edit_post_path(@post), class:"button" %>
		  	</p>
		  	<p class="level-item">
				<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class:"button is-danger" %>
				</p>
		  </div>
		</nav>
		<hr/>


		<div class="content">
			<%= @post.content %>
		</div>
	</div>
</section>

<section class="section comments">
	<div class="container">
		<h2 class="subtitle is-5"><strong><%= @post.comments.count %></strong> Comments</h2>
		<%= render @post.comments %>
		<div class="comment-form">
			<hr />
			<h3 class="subtitle is-3">Leave a reply</h3>
	 		<%= render 'comments/form' %>
		</div>
	</div>
</section>